import { redirect } from "next/navigation";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const me = await fetch(`${process.env.NEXT_PUBLIC_BASE_URL}/auth/me`);
  // const result = await me.json();
  // if (result.message !== "Unauthorized") {
  //   redirect("/main/dashboard");
  // }
  return (
    <main className="bg-gradient-to-r from-background to-slate-700">
      {children}
    </main>
  );
}
